import type { PauWorkspaceSnapshot } from "@/lib/pau/types";

export const demoSnapshot: PauWorkspaceSnapshot = {
  demoMode: true,
  integrationStatus: {
    database: false,
    bitrix: false,
    matching: false,
    openrouter: false,
  },
  autoSync: {
    enabled: false,
    intervalMinutes: 60,
    running: false,
    lastStartedAt: null,
    lastFinishedAt: null,
    lastError: null,
    nextRunAt: null,
    lastLog: null,
  },
  summary: {
    upcomingEvents: 3,
    pastEvents: 2,
    invitedParticipants: 34,
    confirmedParticipants: 21,
    activeParticipants: 8,
    briefs: 6,
  },
  formats: [
    {
      slug: "guest-meeting",
      name: "Гостевая встреча",
      description:
        "Знакомство потенциальных участников с клубом и активными участниками.",
      audience: "Гости, активные участники, модератор",
      moderatorNotes: "Проверить персональные связки и роли активных участников.",
      bitrixEventTypeIds: ["guest-meeting"],
      bitrixSyncTitleQuery: "Гостевая встреча",
      matchingRules: {
        goal: "Релевантные активные участники для доверия и интро.",
      },
      promptPotential:
        "Кратко опиши гостя, его бизнес, возможный запрос и риски встречи.",
      promptActive:
        "Кратко опиши, зачем активному участнику встречаться с гостем и какие темы поднять.",
      promptModerator:
        "Собери карту связок между гостями и активными участниками.",
      promptReport:
        "Сформируй отчет по расшифровке встречи: ключевые темы, решения и следующие шаги.",
    },
    {
      slug: "working-group",
      name: "Рабочая группа",
      description: "Прикладная встреча вокруг бизнес-темы.",
      audience: "Участники с релевантным опытом",
      moderatorNotes: "Вывести участников на конкретные кейсы.",
      bitrixEventTypeIds: ["working-group"],
      bitrixSyncTitleQuery: "Рабочая группа",
      matchingRules: { goal: "Опыт, запрос и тематическая релевантность." },
      promptPotential: "Опиши связь гостя с темой рабочей группы.",
      promptActive: "Опиши вклад активного участника в дискуссию.",
      promptModerator: "Собери план модерации рабочей группы.",
      promptReport: "Сформируй отчет по рабочей группе на основе расшифровки.",
    },
  ],
  upcomingEvents: [
    {
      id: "demo-event-1",
      title: "МСК Гостевая встреча: сообщество как инструмент для бизнеса",
      startsAt: "2026-05-28T16:00:00.000Z",
      endsAt: null,
      status: "UPCOMING",
      bitrixEventId: "20142",
      bitrixSmartItemId: "demo-visit-group-1",
      bitrixEventTypeId: "guest-meeting",
      bitrixEventTypeLabel: "Гостевая встреча",
      formatSlug: "guest-meeting",
      formatName: "Гостевая встреча",
      syncedAt: "2026-05-24T09:00:00.000Z",
      counts: {
        invited: 14,
        confirmed: 9,
        refused: 2,
        attended: 0,
        missed: 0,
        unknown: 3,
        active: 4,
        briefs: 3,
      },
      latestMatch: {
        activeParticipantCount: 4,
        rationale: "Есть пересечение по B2B, комьюнити и инвестиционным запросам.",
        createdAt: "2026-05-24T09:10:00.000Z",
      },
      latestReport: null,
      participants: [
        {
          id: "demo-p1",
          participantId: null,
          kind: "POTENTIAL",
          status: "CONFIRMED",
          bitrixDealId: "146166",
          bitrixContactId: "9001",
          fullName: "Омар Магомедович Омаров",
          email: null,
          phone: null,
          telegram: null,
          company: "Omarov Group",
          position: "Основатель",
          city: "Москва",
          age: 39,
          gender: "Мужской",
          businessMain: "Девелопмент и управление активами",
          businessExtra1: "Инвестиции",
          businessExtra2: "HoReCa",
          businessExtra3: null,
          businessProfile: {
            main: {
              sphere: "Девелопмент и управление активами",
              specifics: null,
              role: "Основатель",
              experience: null,
              okved: null,
              sharePercent: null,
              revenue: null,
              rusprofileUrl: null,
              siteUrl: null,
            },
            extra1: {
              sphere: "Инвестиции",
              specifics: null,
              role: null,
              experience: null,
              okved: null,
              sharePercent: null,
              revenue: null,
              rusprofileUrl: null,
              siteUrl: null,
            },
            extra2: {
              sphere: "HoReCa",
              specifics: null,
              role: null,
              experience: null,
              okved: null,
              sharePercent: null,
              revenue: null,
              rusprofileUrl: null,
              siteUrl: null,
            },
            extra3: null,
          },
          enrichment: {
            additionalInfo: "Запрос на сильное окружение и сделки через доверие.",
          },
          matchedScore: null,
          matchRationale: null,
          attendanceMarked: false,
          activeDecision: null,
          activeDecisionComment: null,
          briefSummary: "Гость с сильным предпринимательским контекстом.",
        },
        {
          id: "demo-a1",
          participantId: null,
          kind: "ACTIVE",
          status: "INVITED",
          bitrixDealId: null,
          bitrixContactId: null,
          fullName: "Анна Иванова",
          email: null,
          phone: null,
          telegram: null,
          company: "Acme",
          position: "CEO",
          city: "Москва",
          age: null,
          gender: null,
          businessMain: "B2B SaaS",
          businessExtra1: null,
          businessExtra2: null,
          businessExtra3: null,
          businessProfile: {
            main: {
              sphere: "B2B SaaS",
              specifics: null,
              role: "CEO",
              experience: null,
              okved: null,
              sharePercent: null,
              revenue: null,
              rusprofileUrl: null,
              siteUrl: null,
            },
            extra1: null,
            extra2: null,
            extra3: null,
          },
          enrichment: null,
          matchedScore: 0.88,
          matchRationale: "Близкий B2B-контекст и опыт построения комьюнити.",
          attendanceMarked: false,
          activeDecision: "INVITED_REFUSED",
          activeDecisionComment: null,
          briefSummary: "Подсветить опыт роста через партнерства.",
        },
      ],
    },
  ],
  pastEvents: [
    {
      id: "demo-event-past",
      title: "СПБ Диалог с экспертом: тренды и применение в бизнесе",
      startsAt: "2026-05-10T15:00:00.000Z",
      endsAt: null,
      status: "PAST",
      bitrixEventId: "17778",
      bitrixSmartItemId: "demo-visit-group-past",
      bitrixEventTypeId: "expert-dialogue",
      bitrixEventTypeLabel: "Диалог с экспертом",
      formatSlug: "working-group",
      formatName: "Рабочая группа",
      syncedAt: "2026-05-11T09:00:00.000Z",
      counts: {
        invited: 20,
        confirmed: 12,
        refused: 3,
        attended: 10,
        missed: 2,
        unknown: 5,
        active: 4,
        briefs: 3,
      },
      latestMatch: null,
      latestReport: {
        id: "demo-report-1",
        summary: "Участники обсудили тренды, договорились обменяться кейсами.",
        createdAt: "2026-05-11T12:00:00.000Z",
      },
      participants: [],
    },
  ],
  briefs: [
    {
      id: "demo-brief-1",
      eventTitle: "МСК Гостевая встреча: сообщество как инструмент для бизнеса",
      participantName: "Анна Иванова",
      briefType: "ACTIVE",
      model: "openai/gpt-5-mini",
      summary: "Подсветить опыт роста через партнерства.",
      createdAt: "2026-05-24T09:12:00.000Z",
      createdByRole: "MANAGER",
    },
  ],
  users: [
    {
      id: "dev-manager",
      login: "manager",
      displayName: "Менеджер",
      role: "MANAGER",
      active: true,
      createdAt: "2026-05-24T09:00:00.000Z",
    },
  ],
};
